PR/PR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parkapp.urls', namespace='parkapp')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('djeym/', include('djeym.urls', namespace='djeym')),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

PR/parkapp/urls.py
from django.urls import path
from parkapp.views import *


app_name = 'parkapp'

urlpatterns = [
    path('', index, name='index'),
    path('register', register, name='register'),
    path('register_admin', register_admin, name='register_admin'),
    path('register_cuckold', register_cuckold, name='register_cuckold'),
    path('login', login, name='login'),
    path('pizdec', pizdec, name='pizdec')
]

PR/parkapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    card_num = models.PositiveBigIntegerField(default=0)
    card_period = models.PositiveIntegerField(default=0)
    card_cvv = models.PositiveIntegerField(default=0)
    rights = models.IntegerField(default=0)
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=20)
    park_id = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.username} | {self.rights}'
    

class Parking(models.Model):
    address = models.CharField(max_length=120, default='')
    registry_nubmer = models.PositiveIntegerField(default=0)
    max_parking_spaces = models.PositiveIntegerField(default=0)
    occupied_places = models.PositiveIntegerField(default=0)
    price_per_minute = models.PositiveIntegerField(default=0)
    free_time = models.PositiveIntegerField(default=15)

    def __str__(self) -> str:
        return f'{self.address} | {self.max_parking_spaces}'


class Reciept(models.Model):
    parking_id = models.ForeignKey(Parking, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    start_time = models.DateTimeField(default=None)
    finish_time = models.DateTimeField(default=None)
    final_price = models.BigIntegerField(default=-1)
    benefit = models.BooleanField(default=False)

    def __str__(self) -> str:   
        return f'{self.start_time} | {self.user_id}'

PR/parkapp/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from parkapp.models import *
from django.urls import reverse
import random
import datetime

from django.shortcuts import render, redirect, HttpResponseRedirect


def index(request):
    if request.method == 'POST':
        if 'create_park' in request.POST:
            user = request.user
            park_id = request.POST.get('park_id')
            parkings = Parking.objects.filter(pk=park_id)
            if parkings:
                parking = parkings[0]
                print(park_id)
                starttime = datetime.datetime.now()
                Reciept.objects.create(parking_id=parking, user_id=user, start_time=starttime, finish_time=starttime)
        elif 'end_park' in request.POST:
            reciept_id = request.POST.get('end_park')
            reciept = Reciept.objects.get(pk=reciept_id)
            reciept.finish_time = datetime.datetime.now()
            # print(reciept.parking_id)
            parking = Parking.objects.get(pk=reciept.parking_id.pk)
            dif = (reciept.finish_time.replace(tzinfo=None) - reciept.start_time.replace(tzinfo=None))
            dif = dif.total_seconds()
            minutes = int(parking.price_per_minute * dif // 60)
            if minutes <= 15:
                reciept.final_price = 0
            else:
                reciept.final_price = int(parking.price_per_minute * dif // 60)
            print(reciept.final_price)
            reciept.save()

    reciepts = Reciept.objects.filter(user_id=request.user, final_price=-1)
    return render(request, 'parkapp/index.html', {'parking': Parking.objects.all(), 'reciepts': reciepts})


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        card_num = request.POST.get('card_num')
        card_period = request.POST.get('card_period')
        card_cvv = request.POST.get('card_cvv')
        user_password = request.POST.get('user_password')
        # print(username, card_num, card_period, card_cvv, user_password)
        User.objects.create(username=username, card_num=card_num, card_period=card_period, card_cvv=card_cvv, password=user_password)
        return HttpResponseRedirect(reverse('parkapp:login'))

    else:
        return render(request, 'parkapp/register.html')

def register_cuckold(request):
    if request.method == 'POST':
        user = request.user
        print(user)
        admins = User.objects.filter(rights=2)
        if user in admins:
            username = request.POST.get('username')
            password = request.POST.get('password')
            park_id = request.POST.get('park_id')
            User.objects.create(username=username, password=password, park_id=park_id, rights=1)
            return HttpResponseRedirect(reverse('parkapp:login'))
        else:
            return render(request, 'parkapp/poshelvon.html')
    return render(request, 'parkapp/register_cuckold.html')

def register_admin(request):
    if request.method == 'POST':
        user = request.user
        print(user)
        admins = User.objects.filter(rights=2)
        if user in admins:
            username = request.POST.get('username')
            password = request.POST.get('password')
            User.objects.create(username=username, password=password, rights=2)
            return HttpResponseRedirect(reverse('parkapp:login'))
        else:
            return render(request, 'parkapp/poshelvon.html')
    return render(request, 'parkapp/register_admin.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username=username, password=password)
            if user:
                auth.login(request, user)
                return redirect(reverse('parkapp:index'))
        except:
            return render(request, 'parkapp/login.html', {'error': 'СОСИ'})
    else:
        return render(request, 'parkapp/login.html')


def pizdec(request):
    return render(request, 'parkapp/pizdec.html')

PR/parkapp/templates/parkapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body text="blue">
    {% if not reciepts %}
    <form method="post" action="/">
        {% csrf_token %}
        <input type="text" name="park_id">E
        <button type="text" name="create_park">
    </form>
    {% else %}
    {% for el in reciepts %}
    <form method="post" action="/">
        {% csrf_token %}
        {{ el }}
        <input type="submit" value="{{el.pk}}" name="end_park">
    </form>
    {% endfor %}
    {% endif %}
    <h1>{{ request.user }}</h1>
    <p>{% for el in parking %}
        {{el.address}}<br>
    {% endfor %}</p>
<!--
    <script src="https://maps.api.2gis.ru/2.0/loader.js?pkg=full"></script>
    <script>
        DG.then(function() {
        map = DG.map('map', {
            'center': [54.98, 82.89],
            'zoom': 13
        });
    });

    </script>
-->
</body>
</html>

PR/parkapp/templates/parkapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'parkapp:login' %}" method='post'>
        {% csrf_token %}
        <input type="text" name="username">name
        <input type="text" name="password">pwd
        <input type="submit">
    </form>
    {{ error }}
</body>
</html>

PR/parkapp/templates/parkapp/pizdec.html
{% load i18n static djeymtags %}

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">

  <!-- START VENDORS CSS -->
  <!-- Roboto Font:
        Usage (css):
          font-size: 16px;
          font-family: Roboto, sans-serif !important;
          font-weight: 100|300|400|500|700|900;
          font-style: italic!important; -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
  <!-- Material Design Icons:
        url: https://materialdesignicons.com/
        Usage (html):
          <span class="mdi mdi-name"></span>
          Size: mdi-18px|mdi-24px|mdi-36px|mdi-48px or font-size: 16px;
          Rotate: mdi-rotate-45|mdi-rotate-90|mdi-rotate-135|mdi-rotate-180|mdi-rotate-225|mdi-rotate-270|mdi-rotate-315
          Flip: mdi-flip-h|mdi-flip-v
          Color: mdi-light|mdi-light mdi-inactive|mdi-dark|mdi-dark mdi-inactive or color: #212121; -->
  <link href="https://cdn.jsdelivr.net/npm/@mdi/font@7.x/css/materialdesignicons.min.css" rel="stylesheet">
  <!-- END VENDORS CSS -->
</head>

<body>
  <!-- START MAP -->
  <!-- Buttons are optional.
       (Кнопки не являются обязательными.) -->
  <style type="text/css">
    .djeym-button {
      font-family: Roboto, sans-serif !important;
      background-color: #4CAF50;
      border: none;
      color: white;
      padding: 10px 24px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 4px 2px;
      cursor: pointer;
    }
    .djeym-button-bar {
      display: none;
      margin-bottom: 10px;
    }
  </style>
  <div class="djeym-button-bar">
    <button id="djeym-open-panel" type="button" class="djeym-button">
      <span class="mdi mdi-arrow-expand-right"></span>
      Open Panel
    </button>
    <button id="djeym-add-marker" type="button" class="djeym-button">
      <span class="mdi mdi-map-marker-plus"></span>
      Add Marker
    </button>
  </div>
  <div id="djeym-app" class="djeym"></div>
  <!-- END MAP -->

  <!-- START VENDORS JS -->
  <script type="text/javascript" src="{% static "djeym/js/jquery.min.js" %}"></script>
  <script src="{% static "djeym/js/jquery-regex.min.js" %}"></script>
  ...
  {% djeym_yandex_map slug='test-map' lang=request.LANGUAGE_CODE %}
  <!-- END VENDORS JS -->
</body>

PR/parkapp/templates/parkapp/poshelvon.html
ИДИ НАХУЙ

PR/parkapp/templates/parkapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <form action="{% url 'parkapp:register' %}" method='post'>
        {% csrf_token %}
        <input type="text" name="username">name
        <input type="text" name="card_num">cardnum
        <input type="text" name="card_period">cardperiod
        <input type="text" name="card_cvv">cvv
        <input type="text" name="user_password">pwd
        <input type="submit">
    </form>
</body>
</html>

PR/parkapp/templates/parkapp/register_admin.html
XD2

PR/parkapp/templates/parkapp/register_cuckold.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'parkapp:register_cuckold' %}" method='post'>
        {% csrf_token %}
        <input type="text" name="username">name
        <input type="text" name="password">pwd
        <input type="text" name="park_id">park_id
        <input type="submit">
    </form>
    {{ error }}
</body>
</html>